### ISSUE TITLE
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

### ISSUE THREAD

**Issue by bguscott** [pR0Ps/slack-to-discord#3]
Hello,

First of all, great project! However, when I try to run `slack-to-discord --zipfile <slack export zip> --guild <guild name> --token <bot token>` I receive an error when trying to connect to Discord.

## Issue:

When I try to execute the latest commit (`42410d4c1e5492d4f30b9998af4ee6390f1c7d81` - I have not tried any other commits) I receive the following error:

```
Extracting zipfile...Done!
Logging the bot into Discord...Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\Scripts\slack-to-discord-script.py", line 33, in <module>
    sys.exit(load_entry_point('slack-to-discord==0.0.1', 'console_scripts', 'slack-to-discord')())
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\slack_to_discord.py", line 472, in main
    client = MyClient(
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\slack_to_discord.py", line 351, in __init__
    super().__init__(*args, **kwargs)
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'
```

## What I have done:

1. Created a discord bot and added to my server per the instructions in the README:
![image](https://user-images.githubusercontent.com/32576039/187099915-d36ec04b-136c-46f1-9d4e-bda89b3bc6b6.png)
2. Installed the latest commit via pip on my Windows 11 machine
3. Tried enabling all Privileged Gateway Intents (makes no difference):
![image](https://user-images.githubusercontent.com/32576039/187100012-9b4fa113-3fa5-4115-b9f8-464a68ef9e6f.png)

**Comment by bguscott** [comment]
Closing - I thought I was using the latest commit but I wasn't :) 

Using `42410d4c1e5492d4f30b9998af4ee6390f1c7d81` seems to work - the discord bot was able to login.
